### ISSUE TITLE
Teresa API could support gRPC

### ISSUE THREAD

**Issue by diegofernandes** [luizalabs/teresa-api#161]
gRPC could help on clients in differents languages, performance, bi-direction streams, etc.

**Comment by alexguerra-luizalabs** [comment]
I'm not sure but I guess it should work right away as teresa by default creates a TCP load balanced service.
Can you help us test it?

**Comment by aguerra** [comment]
Sorry, I misunderstood the description the first time. Yes, I would say that gRPC is on the top of list for testing.

**Comment by drgarcia1986** [comment]
WIP!
